# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='work_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Numero de Archivo')),
                ('actual_process', models.IntegerField(default='0')),
                ('status', models.CharField(default='pendiente', max_length=10)),
                ('accumulated_time', models.CharField(default='0', max_length=100)),
                ('actual_time', models.CharField(default='0', max_length=100)),
                ('ini_date_process', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_date_process', models.DateTimeField(null=True)),
                ('ini_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_process1', models.CharField(default='-', max_length=100)),
                ('time_process2', models.CharField(default='-', max_length=100)),
                ('time_process3', models.CharField(default='-', max_length=100)),
                ('time_process4', models.CharField(default='-', max_length=100)),
                ('status_one', models.CharField(default='pendiente', max_length=10)),
                ('status_two', models.CharField(default='pendiente', max_length=10)),
                ('status_three', models.CharField(default='pendiente', max_length=10)),
                ('status_four', models.CharField(default='pendiente', max_length=10)),
                ('ini_date_process1', models.DateTimeField(default=django.utils.timezone.now)),
                ('ini_date_process2', models.DateTimeField(default=django.utils.timezone.now)),
                ('ini_date_process3', models.DateTimeField(default=django.utils.timezone.now)),
                ('ini_date_process4', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_date_process1', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_date_process2', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_date_process3', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_date_process4', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
