# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170524_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_file',
            name='finish_date_process1',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
