# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20170529_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_file',
            name='finish_date_process',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
